### ISSUE TITLE
Contact information not being generated correctly

### ISSUE THREAD

**Issue by jpbottinelli** [quarentime/quarentime-back-end#31]
When a user invites another one, the /User/Contacts endpoint of the receiver of the invitation doesn't show the data correctly.
Steps to reproduce:
**User 1 Personal Information**
```
{
    "result": {
        "user_id": "WpborYg18uY9kRdX4lGxfMzlhpz2",
        "email": "test_quarentime_user1@quarentime-test.com",
        "name": "Test",
        "surname": "New User 1",
        "age": 34,
        "phone_number": "1234567890",
        "verified": false,
        "display_name": "Test New User 1"
    },
    "request_id": "c960ce99-2725-45f5-b499-8eea1f90ad28"
}

```

**User 2 Personal Information**
```
{
    "result": {
        "user_id": "xsok9py51egOCrUcbJ6C7xP3EAk1",
        "email": "test_quarentime_user2@quarentime-test.com",
        "name": "Test",
        "surname": "New User 2",
        "age": 34,
        "phone_number": "0123456789",
        "verified": false,
        "display_name": "Test New User 2"
    },
    "request_id": "e43c1b46-d62c-4e5d-8fae-d6e8526ed3ae"
}
```

**Invitation request from User 2 to User 1** 
```
{
	"contacts": [
		{
			"user_id": "WpborYg18uY9kRdX4lGxfMzlhpz2",
			"name": "Test",
			"surname": "New User 1",
			"phone_number": "1234567890"
		}
	]
}
```

When validating that the contacts for both users were successfully generated (before Accepting/Rejecting it), I expect to see the following:
**GET /User/Contact User 1**
Expectation: Show information of User 2
```
{
            "name": "Test",
            "phone_number": "0123456789",
            "user_id": "xsok9py51egOCrUcbJ6C7xP3EAk1",
            "date_added": "2020-04-04T16:54:42.514453Z",
            "status": "healthy",
            "pending": false
        },
```

Actual Result:
```
{
            "name": "Test",
            "phone_number": "1234567890",
            "user_id": "WpborYg18uY9kRdX4lGxfMzlhpz2",
            "date_added": "2020-04-04T16:54:42.514453Z",
            "status": "healthy",
            "pending": false
        },
```

**GET /User/Contact User 2**
Expectation: Show information of User 1
```
{
            "name": "Test",
            "phone_number": "1234567890",
            "user_id": "WpborYg18uY9kRdX4lGxfMzlhpz2",
            "date_added": "2020-04-04T16:54:42.514453Z",
            "status": "healthy",
            "pending": false
        },
```

Actual Result: ok

Unless I'm misunderstanding the flow, I think this is an important bug that should be reflecting in the App.

**Comment by edmarsj** [comment]
The receiving user should not see the invitation on its contact endpoint. But on the /FriendRequests/Pending endpoint. 
Is this confusing? Do you think it would be better to centralize in only one endpoint @jpbottinelli? Please, let have a chat about this.

**Comment by jpbottinelli** [comment]
It's ok to have two endpoints as long as the information is consistent. I think there should be is just 1 invitation per pair of Contacts.
If user A invites B, then there should be 1 invitation saying to/from and no other invitation should be created if the to and from are from the same pair of users.
If B then invites A, the response of the API could be 2 things that I can think of:
* as we detect that there's an invitation from A to B, we accept it, so no invitation is sent, we just close the loop. The response could be 200 with a message saying something like 'as there was a pending invitation from that user, that invitation was accepted'
* The API returns 409 and a message saying: 'There's a pending invitation from that user, accept it in the Pending Invitations page'
We can discuss via Slack, but I think the most important thing is the validation that the invitations are just 1 per pair of users, regardless of who sent the invitation.
It's completely up to you and the user experience that we want to give

**Comment by edmarsj** [comment]
Fixed the cross double invitation issue by adding the contact straight away, when we invite someone who invited us. 
The API will also return statuses of each individual operation, eg.

```json
{
    "result": [
        {
            "phone_number": "+99999999",
            "result": "invitation_sent"
        },
       {
            "phone_number": "+0000000",
            "result": "already_exists"
        },
       {
            "phone_number": "+111111",
            "result": "invitation_accepted"
        }
    ],
    "request_id": "bc9bd146-01a8-4747-a4ad-6d2250debdb9"
}```

**Comment by jpbottinelli** [comment]
@edmarsj 
After the fix, I started to see another issue:

Now with user 1 I accept the invitation, but in the /Contacts endpoint I still see the status 'pending' and is_direct_contact 'false', but also pending false:
```
    "result": [
        {
            "name": "test_quarentime_user_2_1587844124281 New User 2",
            "phone_number": "+11587844124281",
            "user_id": "JREiPWesNFfQ4AqRth4o7gda5gu1",
            "date_added": "2020-04-25T20:02:13.919253Z",
            "status": "pending",
            "is_direct_contact": false,
            "pending": false
        }
    ],
    "request_id": "1a2c1b5d-7b3a-4737-a669-42a02574a705"
}
```

Looks like we have an inconsistency issue. I don't know if pending and is_direct_contact fields are necessary. If the are we should fix them, otherwise I'd remove them.

Same issue happens with user 2 who sent the invitation.

```
    "result": [
        {
            "name": "test_quarentime_user_1_1587844086972",
            "phone_number": "+11587844086972",
            "user_id": "Hf7UfI5CU5cxNI2hFaL4fP2J9Gf1",
            "date_added": "2020-04-25T20:02:14.309892Z",
            "status": "pending",
            "is_direct_contact": false,
            "pending": false
        }
    ],
    "request_id": "1929b27b-511d-4e17-8a20-74991f8f1ab5"
}
```
